main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('wines/', views.wines_index, name='index'),
    path('wines/<int:wine_id>/', views.wines_detail, name='detail'),
    path('wines/create/', views.WineCreate.as_view(), name='wines_create'),
    path('wines/<int:pk>/update/', views.WineUpdate.as_view(), name='wines_update'),
    path('wines/<int:pk>/delete/', views.WineDelete.as_view(), name='wines_delete'),
    path('wines/<int:wine_id>/add_year/', views.add_year, name='add_year'),
    path('wines/<int:wine_id>/assoc_food/<int:food_id>', views.assoc_food, name='assoc_food'),
    path('wines/<int:wine_id>/remove_food/<int:food_id>', views.remove_food, name='remove_food'),
    path('wines/<int:wine_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
] 

winecollector_project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Food(models.Model):
    name = models.CharField(max_length=50)
    # Other goodness such as 'def __str__():' below
    def __str__(self):
        return f'{self.name}'

    # Add this method
    def get_absolute_url(self):
        return reverse('food_detail', kwargs={'food_id': self.id})    
        class Meta:
            ordering = ['-date']

class Wine(models.Model):
    name = models.CharField(max_length=100)
    winetype = models.CharField(max_length=100)
    cost = models.IntegerField()
    foods = models.ManyToManyField(Food)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

# Create your models here.
    def get_absolute_url(self):
        return reverse('detail', kwargs={'wine_id': self.id})

class Year(models.Model):
    year = models.IntegerField()
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)


def get_absolute_url(self):
    return reverse('detail', kwargs={'wine_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for wine_id: {self.wine_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Year

class YearForm(ModelForm):
    class Meta:
        model = Year
        fields = ['year']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Wine, Food, Photo
from .forms import YearForm

# Add the following import
from django.http import HttpResponse

import uuid
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'winecollector'

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def wines_index(request):
    wines = Wine.objects.filter(user=request.user)
    return render(request, 'wines/index.html', { 'wines': wines })


def wines_detail(request, wine_id):
    wine = Wine.objects.get(id=wine_id)
    foods_wine_doesnt_have = Food.objects.exclude(id__in = wine.foods.all().values_list('id'))
    year_form = YearForm()
    return render(request, 'wines/detail.html', { 
        'wine': wine, 'year_form':year_form,
        'foods': foods_wine_doesnt_have
    })

def add_year(request, wine_id):
    form = YearForm(request.POST)
    # validate the form
    if form.is_valid():
        new_year = form.save(commit=False)
        new_year.wine_id = wine_id
        new_year.save()
    return redirect('detail', wine_id=wine_id)

class WineCreate(LoginRequiredMixin, CreateView):
    model = Wine
    fields = ['name', 'winetype', 'cost']
    success_url = '/wines/'
    def form_valid(self, form):
    # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the wine
    # Let the CreateView do its job as usual
        return super().form_valid(form)

class WineUpdate(UpdateView):
    model = Wine
    fields = ['winetype', 'cost']

class WineDelete(DeleteView):
    model = Wine
    success_url = '/wines/'


def foods_index(request):
    foods = Food.objects.all()
    context = {'foods': foods}
    
    return render(request, 'food/index.html', context)

def food_detail(request, food_id):
    food = Food.objects.get(id=food_id)
    context = {
        'food': food
    }
    return render(request, 'food/detail.html', context)
    
class Create_Food(CreateView):
    model = Food
    fields = '__all__'

class Delete_food(DeleteView):
    model = Food
    success_url = '/foods/'     

def assoc_food(request, wine_id, food_id):
    Wine.objects.get(id=wine_id).foods.add(food_id)
    return redirect('detail', wine_id=wine_id)

def remove_food(request, wine_id, food_id):
    Wine.objects.get(id=wine_id).foods.remove(food_id)
    return redirect('detail', wine_id=wine_id)

def add_photo(request, wine_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, wine_id=wine_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', wine_id=wine_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Wine Collector</h1>
<hr />
<p>Hire the Wine Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Wine Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;WineCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'wines_create' %}">Add a Wine</a></li>
            <li><a href="{% url 'index' %}">View All My Wine</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2021 Wine Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/wine_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Wine</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' wine.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/wine_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Wine</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/wines/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Wine Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ wine.name }}</span>
        <p>Type: {{ wine.winetype }}</p>
        <p>Cost: ${{ wine.cost }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'wines_update' wine.id %}">Edit</a>
        <a href="{% url 'wines_delete' wine.id %}">Delete</a>
      </div>
    </div>
    {% for photo in wine.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    <form
      action="{% url 'add_photo' wine.id %}"
      enctype="multipart/form-data"
      method="POST"
      class="card-panel"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" class="btn" value="Upload Photo" />
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_year' wine.id %}" method="post">
      {% csrf_token %} {{ year_form.as_p }}
      <input type="submit" class="btn" value="Add Year" />
    </form>

    <table class="striped">
      <thead>
        <tr>
          <th>Year</th>
        </tr>
      </thead>
      <tbody>
        {% for year in wine.year_set.all %}
        <tr>
          <td>{{year.year}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ wine.name }} Food Pairing</h3>
    {% if wine.foods.count %} {% for food in wine.foods.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ food.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'remove_food' wine.id food.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn red">Remove</button>
        </form>
      </div>
    </div>

    {% endfor %} {% else %}
    <h5>No Food Pairing Yet!</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Food Right Now</h3>
    {% if foods.count %} {% for food in foods.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ food.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_food' wine.id food.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{wine.name}} Already Has All Food Paired</h5>
    {% endif %}
  </div>
  {% endblock %}
</div>

main_app/templates/wines/index.html
{% extends 'base.html' %} {% block content %}

<h1>Wine List</h1>

{% for wine in wines %}
<div class="card">
  <a href="{% url 'detail' wine.id %}">
    <div class="card-content">
      <span class="card-title">{{ wine.name }}</span>
      <p>Type: {{ wine.winetype }}</p>
      <p>Cost: ${{ wine.cost }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}